### PR TITLE
Implement Mergesort in C.

### LINKED ISSUE #22: Add mergesort in C

### PR DESCRIPTION
**Pull request by ilimugur**
Resolve #22

### CODE REVIEW

**Comment by ilimugur** [comment]
Let me know if you encounter any issues with the code, or request any improvements.

**Comment by thecodershub** [comment]
Kindly use asserts for tests, in line with the other languages in the repository.

**Comment by ilimugur** [comment]
OK, I'll update all my pull requests accordingly.

**Comment by ilimugur** [comment]
@thecodershub I replaced the if statements in tests with assertions in this pull requests and also in the ones resolving issues #21 & #23

**Pull request merged**
